Adding concepts for Dual Duct HVAC systems
BrickSchema/Brick pull request #378
Opened 2022-03-03 18:16 UTC by lazlop

Added concepts for dual duct HVAC systems as mentioned in #376

2022-03-29 05:22 UTC, gtfierro commented
@lazlop let me know when you get a chance to come back to this and make the edits we discussed on the ontology working group call last week!

2022-03-29 20:13 UTC, lazlop commented
@gtfierro Sorry, the end of March has been pretty busy and I just got around to this! This is my first attempt at writing a SHACL shape, let me know if it looks right. Also, let me know where the location of the SHACL shape should be. Just added it to BrickEntityShapeBase.ttl for now

2022-03-29 21:39 UTC, gtfierro requested changes
No worries @lazlop! I made a couple small suggestions but I think this is very close

2022-03-29 21:39 UTC, gtfierro commented on bricksrc/equipment.py
> +            "Dual_Duct_Air Handling Unit": {
You will need underscores instead of spaces here

2022-03-29 21:39 UTC, gtfierro commented on shacl/BrickEntityShapeBase.ttl
> +bch:hasHotColdDeck
This should be 'bsh' instead of 'bch'

2022-03-30 17:56 UTC, gtfierro approved these changes

2022-03-30 21:55 UTC, merged

2022-03-30 21:55 UTC, gtfierro commented
Thanks @lazlop!