Make tests run in windows
BrickSchema/Brick pull request #443
Opened 2022-10-13 20:31 UTC by Gamecock

Fixes #438 

Address differences in encoding between nix and windows
Works around https://github.com/RDFLib/rdflib/issues/2067 in serialize
Deletes artifacts from tests
Updates README.md and CONTRIBUTING.md

2022-10-13 20:36 UTC, Gamecock commented
pre-commit checks not run.  The corporate ssl checks on my machine defeated me.

2022-11-26 18:26 UTC, gtfierro requested changes
One tiny change and then this is good to merge. Thanks so much for taking the time to make these changes!

2022-11-26 18:26 UTC, gtfierro commented on README.md
> +* Before running `pytest` the Brick.ttl file needs to be created using either `make` or `py generate_brick.py`.
`python generate_brick.py`

2022-11-26 18:27 UTC, gtfierro approved these changes

2022-11-26 18:47 UTC, merged